name: Sync

on:
  workflow_call:
    inputs: 
      appName:
        required: true
        type: string
    secrets:
      STRUXHUB_GPR_TOKEN:
        required: true

jobs:
  sync:
    if: github.event.comment.body == '/sync'
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ inputs.STRUXHUB_GPR_TOKEN }}
          fetch-depth: 0

      - name: Fetch repository history
        run: |
          git fetch
          git pull --tags

      - name: Get Pull Request Data
        id: pr
        uses: simpleactions/get-pull-request@v1.0.0
        with:
          github_token: ${{inputs.STRUXHUB_GPR_TOKEN}}
          pull_number: ${{ github.event.issue.number }}

      - name: Rebase ${{ steps.pr.outputs.base_ref }} to the tip of ${{ steps.pr.outputs.head_ref }}
        run: |
          git config user.name struxhub-bot
          git config user.email admin@struxhub.com

          git checkout ${{ steps.pr.outputs.head_ref }}
          git checkout ${{ steps.pr.outputs.base_ref }}

          git rebase ${{ steps.pr.outputs.head_ref }}

          git push --force origin ${{ steps.pr.outputs.base_ref }}

      - name: Add merge comment (failure)
        if: failure()
        uses: simpleactions/create-issue-comment@v1.0.0
        with:
          github_token: ${{inputs.STRUXHUB_GPR_TOKEN}}
          issue_number: ${{ github.event.issue.number }}
          body: |
            Sync failed.

            Follow those steps to manually sync:

            ```
            git checkout ${{ steps.pr.outputs.head_ref }}
            git pull
            git checkout ${{ steps.pr.outputs.base_ref }}
            git pull
            git rebase ${{ steps.pr.outputs.head_ref }}
            ```

            Solve the conflicts, then forcibly push your changes:

            ```
            git push --force origin ${{ steps.pr.outputs.base_ref }}
            ```
