name: Show Help

on:
  workflow_call:
    secrets:
      STRUXHUB_GPR_TOKEN:
        required: true

jobs:
  help:
    if: github.event.comment.body == '/help'
    name: Show Help
    runs-on: ubuntu-latest
    steps:
      - name: Show command help
        uses: simpleactions/create-issue-comment@v1.0.0
        with:
          github_token: ${{secrets.STRUXHUB_GPR_TOKEN}}
          issue_number: ${{ github.event.issue.number }}
          body: |
            ```
            Available commands:

            /merge
              merge this pull request using fast fast-forward

            /rollback <env> <version>
              rollback <env> environment to <version> version

            /release
              release new packages version
            ```