name: 'PR Naming Rules'

on:
  workflow_call:

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          # Regex the title should match.
          # regular pr: 'f/0000/feature name'
          # release pr: 'release/0.0.1'
          # Dependabot pr: 'Bump twilio from 5.60.0 to 5.67.0' created automatically by a bot.
          regex: '^(.+\/[0-9]+\/.+)|(release\/([0-9]+)\.([0-9]+)\.([0-9]+))|(Bump .+)$'
          allowed_prefixes: 'feature,f,bug,b,chore,c,enhancement,hotfix,release,td,Bump ,' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 10 # Min length of the title
          max_length: -1 # Max length of the title
